### ISSUE TITLE
Add back moving of virtual nodes and try to find the bug that crashes it.

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#2]
commit: 5d60839a54458962c1c1511d44dcfb75f5c5c0ef  removed the ability to move virtual nodes.

This feature is needed to easily create new nodes in an existing way and simultaneously move them to their new position.

I have been able to segfault merkaartor by moving ordinary nodes, just much more rarely than by moving virtual nodes. So the underlaying bug might still be present if the same code is used to move ordinary and virtual nodes.

**Comment by Krakonos** [comment]
Re-enabled in e293095. Seems to be working fine, please, test.

**Comment by RM87** [comment]
Sadly this bug still exists. Now it just crashes immediately when moving a virtual node.
Beginning of the backtrace is even more problematic:
#0  0x0000000000000000 in ?? ()
#1  0x00000000005cabf8 in FeatureSnapInteraction::paintEvent(QPaintEvent*, QPainter&) () at Interactions/Interaction.cpp:351
#2  0x0000000000494af9 in MapView::paintEvent(QPaintEvent*) ()
    at common/MapView.cpp:312
#3  0x00007ffff3e884d8 in QWidget::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4

**Comment by Krakonos** [comment]
Strange, I can't reproduce this. Could you please recompile and check with fresh build? It seems rather non-related to the stuff I fixed.

**Comment by RM87** [comment]
Just in case recompiled in a clean folder, but it still crashes.

**Comment by RM87** [comment]
Found a place where creating a virtual node always crashes (at least on my machine)
http://www.openstreetmap.org/#map=19/59.41126/24.79484

Otherwise it has been strangely stable recently.

**Comment by Krakonos** [comment]
Well, at least I added the #map= parsing in Download dialog. Unfortunately, I still can't reproduce the problem you describe, on multiple machines. Still looking into it.

**Comment by Krakonos** [comment]
Fixed in 86051f9edc227864301ade2f5e683a71297dd3a9, in the qt5 branch. Could you check please?

**Comment by RM87** [comment]
This seems to be fixed now (at least no crash on my machine)
