### ISSUE TITLE
Problem while inserting TMS server

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/merkaartor#88]
I am trying to insert this
`http://a.tiles.mapbox.com/v3/tmpsantos.hgda0m6h/%1/%2/%3.png`
 as a new TMS server but somehow Merkaartor is converting it to
`http://a.tiles.mapbox.com/v3/tmpsantos.hgda0m6h/%251/%252/%253.png`

Note that it's inserting **25** after each **%**

Do you need more information about this, please?

Merkaartor version is 0.18.2

**Comment by Krakonos** [comment]
%25 is an escape code for the % character. I guess this is only happening if you click "Get services", which causes a query to the server, without replaced actual coordinates in place of the %i. Just save it and use it, should work fine.

Honestly, I'm not sure what the correct query should be, and I will at least fix the error message, so it actually says what went wrong. The fix will be available in 0.18.3

I won't fix the TMS stuff now, as I plan rather big rewrite of this part for the next version.

**Comment by naoliv** [comment]
It happens without clicking `Get services` too.

**Comment by Krakonos** [comment]
Should be fixed in ddec5c13f2b719de898b2aecc811b2917a25ad67

**Comment by naoliv** [comment]
It isn't fixed
See this video and you should understand what is the problem, please:
http://naoliv.iq.unesp.br/osm/merkaartor-tms.ogv

**Comment by naoliv** [comment]
See how I just insert the URL, click `Add` (I don't click `Get Services`) and Merkaartor inserts `%25` at the URL

**Comment by Krakonos** [comment]
Ah, thanks, thats a bit different than I thought!

**Comment by Totor2015** [comment]
Hi, 
I can confirm this on Windows with 0.18.2-74-g2bc386b-32bit and 0.18.2-73-g223ee66-64bit.exe.
As soon as a TMS service is edited using the gui, the % is replaced with %25 in the xml file.
before edit:  
<TmsServer maxzoom="17" minzoom="0" name="OSM.org Mapnik" address="http://tile.openstreetmap.org" projection="EPSG:900913" tilesize="256" path="/%1/%2/%3.png"/>
after edit:   
<TmsServer maxzoom="17" minzoom="0" name="OSM.org Mapnik" address="http://tile.openstreetmap.org" projection="EPSG:900913" tilesize="256" path="/%251/%252/%253.png"/>

Proxy log after edit shows following failed connections for instance:
http://tile.openstreetmap.org/691951/691952/691953.png
http://tile.openstreetmap.org/691851/691852/691853.png
http://tile.openstreetmap.org/691551/691552/691553.png
http://tile.openstreetmap.org/345651/345652/345653.png
http://tile.openstreetmap.org/345651/345652/345653.png
http://tile.openstreetmap.org/345651/345652/345653.png

On Ubuntu I did not see any problem after a GUI edit, but I discovered that there my Merkaartor uses online configuration and not the xml files in ~/.merkaartor (and I don't know anymore how to disable that ^_^)

Cheers

**Comment by Krakonos** [comment]
Yey, the online configuration. It will probably get removed for 0.19, or at least changed so that everything is stored locally XOR online (if you choose to).

**Comment by Krakonos** [comment]
I'm kicking this can down the road, as it will get major rewrite in the near future and it isn't worth fixing now.

**Comment by Totor2015** [comment]
I understand your point...
For other users:
Until the %25 bug is fixed, new tms can only be added by editing the  TmsServerList.xml file in the (hidden) .merkaartor folder.

**Comment by lebedelankol** [comment]
Hi! Sorry for the offtop, but I can`t set TMS DigitalGlobe Standard Imagery in Merkaartor (latest). I write url from here: https://josm.openstreetmap.de/wiki/Maps#DigitalGlobeStandardImagery, but it doesn`t work. Is it possible? Can you explain how coreectly write every parameter of TMS for example - for DGStandard? I find nothing about it in Merkaartor documentation.
