### ISSUE TITLE
Background is not refreshed on keyboard move

### ISSUE THREAD

**Issue by Totor2015** [openstreetmap/merkaartor#92]
This is a very old bug, on all platforms.
When the arrow keys are used to move the map, the background images (TMS, Bing) are not updated.
A keyboard zoom with + or - , or a mouse drag, refreshes the background correctly.

**Comment by Krakonos** [comment]
Fixed, thanks for reporting and let me know if it causes some problems. The code doing that was commented way back in 2012 and I'm not sure why. My best guess is that it caused some race conditions in the early threaded rendering code, but it should not now.

**Comment by Totor2015** [comment]
I confirm this works now.
Thanks

**Comment by wirepiper** [comment]
This bug is still effecting my use of Merkaartor in Fedora 23.

When ever I try to pan the map window content (i.e., using the keyboard arrow keys), Bing Maps background tile images are not refreshed -- instead blanks squares for tiles appear on the screen. This can happen at any zoom level. In order to refresh the screen I would have to zoom out and then zoom in again to the area being viewed.

I am using:

Fedora 23, with all of the latest software updates installed.

# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree

merkaartor-0.18.2-1.fc23.x86_64

Please confirm this problem.

ASIDE:

Is it possible to add a Window Refresh command in a future release of Merkaartor (maybe v.0.19.x). This can serve as a work around for the Image Background Refresh bug.

Thank you.

**Comment by Krakonos** [comment]
It seems that FC23 has old version of Merkaartor, the current version is 0.18.3, which is the first release that contains the fix. Please, try with the 0.18.3 release and possibly fill a request to update the package.

**Comment by wirepiper** [comment]
To: Ladislav Láska (Krakonos):

First, let me send a sincere thank you for all of the great work you are doing for Merkaartor and OpenStreetMap. I really appreciate your very valuable contribution and your quick response to trouble ticket request from users like me.

Second, it appears as if there are no active maintainers for the Fedora Merkaartor software package. The latest release for Fedora (Stable or Rawhide version) is (merkaartor-0.18.2-3.fc24.x86_64.rpm).

Third, Merkaartor bug reports (https://bugzilla.redhat.com/buglist.cgi?quicksearch=merkaartor) that I filed more than a year ago are still opened and nobody has responded to it. The Redhat Bugzilla has assigned Sven Lankes as the maintainer, but it appears as though he hasn't been active since the year 2013. I am afraid Fedora might drop future releases of Merkaartor from its repositories.

Finally, I was able to build a custom version of Merkaartor Fedora package (merkaartor-0.18.3-1.fc23.x86_64.rpm) for my personal use. If there is anyone else who might need merkaartor-0.18.3 for Fedora, I can provide the specfile (merkaartor.spec) to build the RPM package, or the actual (merkaartor-0.18.3-1.fc23.x86_64.rpm) binary file.

After installing this release update (merkaartor-0.18.3) my problem (Background Image Refresh Bug) is now solved. If there is anything that I can do to help improve Merkaartor and OpenStreetMap, please let me know.

Thank you once again for everything. Please keep up the good work you are doing.

__PEA__

**Comment by Krakonos** [comment]
I'm glad you were able to build your own package. It would be helpful if you could povide the spec file for the 0.18.3 release. The best place would probably be the redhat bugzilla, but be sure to email me the link once you post it.

I already wrote to Sven, but he didn't respond. Though I know for sure he is alive and responds from time to time, the latest email from him is at the end of september 2016. I guess he's a busy man!

Having the spec file might help him do the job fast enough, so it's a good thing!
